### PR TITLE
Add .travis.yml

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

https://travis-ci.org/gliptak/cgpm/builds/284763071

### CODE REVIEW

**Comment by gliptak** [comment]
@fsaad Please review. Thanks

**Comment by fsaad** [comment]
Hi @gliptak thank you for the pull request. We are currently not using Travis for testing this project, and instead are hosting a Jenkins test server on https://probcomp-4.csail.mit.edu. I believe there is some ongoing work by @avinson and @zane  which aims to use Travis, which lives in `https://github.com/probcomp/cgpm/compare/travis`.

**Comment by gliptak** [comment]
@faad As per above, this is a working Travis. Is there a reason to not to add this initially? Thanks

**Comment by avinson** [comment]
@gliptak the reason it's not merged yes is we don't have a working travis branch for all of the probcomp repos (in particular, I'm still working out some issues with bayeslite). After that's ready, we'll merge the branches at the same time along with adding a version tag to master. 

with regards to your travis.yml specifically, it doesn't suit our purposes as we need a more complex file that can push packages to anaconda.org based on tags, branches, etc.

**Pull request closed without merging**
